apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MONGO_HOSTNAME: "mongo-mongodb-replicaset-0.mongo-mongodb-replicaset.default.svc.cluster.local,mongo-mongodb-replicaset-1.mongo-mongodb-replicaset.default.svc.cluster.local,mongo-mongodb-replicaset-2.mongo-mongodb-replicaset.default.svc.cluster.local"  
  MONGO_PORT: "27017"
  MONGO_DB: "strokey-nonce"
  MONGO_REPLICASET: "db"
  # cant resolve the service name for some reason, need to fix this!
  PGHOST: "10.245.80.198"
  PGPORT: "5432"
  PGDATABASE: strokey-nonce
